/* The following code was generated by JFlex 1.4.3 on 10/26/15 6:43 PM */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 2000 Gerwin Klein <lsf@jflex.de>                          *
 * All rights reserved.                                                    *
 *                                                                         *
 * Thanks to Larry Bell and Bob Jamison for suggestions and comments.      *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
package edu.eltech.moevm.autogen;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/26/15 6:43 PM from the specification file
 * <tt>grammar.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\46\1\0\1\0\23\0\1\0\1\57\1\50\2\0"+
    "\1\71\1\54\1\44\1\65\1\66\1\15\1\53\1\63\1\5\1\47"+
    "\1\14\1\42\11\1\1\64\1\60\1\52\1\56\1\51\1\73\1\0"+
    "\4\3\1\4\1\7\5\2\1\11\10\2\1\13\2\2\1\43\2\2"+
    "\1\67\1\45\1\70\1\72\1\2\1\0\1\16\1\21\1\25\1\31"+
    "\1\23\1\6\1\33\1\27\1\34\1\2\1\24\1\10\1\32\1\30"+
    "\1\20\1\40\1\2\1\22\1\26\1\17\1\12\1\41\1\36\1\43"+
    "\1\37\1\35\1\61\1\55\1\62\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\4\3\1\5\1\6"+
    "\14\3\1\2\1\1\1\7\1\1\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\0\2\2\1\33\1\34\3\3\1\0\16\3\1\35"+
    "\2\3\1\36\3\3\5\0\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\2\1\0"+
    "\1\2\1\3\1\51\26\3\1\52\2\3\1\2\1\53"+
    "\1\3\1\54\2\3\1\55\4\3\1\56\1\57\1\60"+
    "\1\3\1\61\10\3\1\62\1\3\1\63\1\64\1\3"+
    "\1\65\1\3\1\66\2\3\1\67\2\3\1\70\5\3"+
    "\1\71\2\3\1\72\1\3\1\73\1\74\1\75\1\76"+
    "\1\77\1\100\2\3\1\101\1\3\1\102\1\103\1\104";

  private static int [] zzUnpackAction() {
    int [] result = new int[182];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\u012c\0\u0168\0\u01a4"+
    "\0\u01e0\0\u021c\0\74\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348"+
    "\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528"+
    "\0\u0564\0\u05a0\0\u05dc\0\u0618\0\u0654\0\u0690\0\u06cc\0\u0708"+
    "\0\u0744\0\u0780\0\74\0\74\0\74\0\74\0\74\0\74"+
    "\0\74\0\74\0\74\0\74\0\74\0\74\0\u07bc\0\u07f8"+
    "\0\u0834\0\74\0\74\0\u0870\0\u08ac\0\u08e8\0\u0564\0\u0924"+
    "\0\u0960\0\u099c\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04"+
    "\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4"+
    "\0\264\0\u0d20\0\u0d5c\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88"+
    "\0\u05dc\0\u05dc\0\74\0\74\0\74\0\74\0\74\0\74"+
    "\0\74\0\74\0\74\0\u0ec4\0\u0f00\0\74\0\u0f3c\0\264"+
    "\0\u0f78\0\u0fb4\0\u0ff0\0\u102c\0\u1068\0\u10a4\0\u10e0\0\u111c"+
    "\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284\0\u12c0\0\u12fc"+
    "\0\u1338\0\u1374\0\u13b0\0\u13ec\0\u1428\0\u1464\0\264\0\u14a0"+
    "\0\u14dc\0\u1518\0\74\0\u1554\0\264\0\u1590\0\u15cc\0\264"+
    "\0\u1608\0\u1644\0\u1680\0\u16bc\0\264\0\264\0\264\0\u16f8"+
    "\0\264\0\u1734\0\u1770\0\u17ac\0\u17e8\0\u1824\0\u1860\0\u189c"+
    "\0\u18d8\0\264\0\u1914\0\264\0\264\0\u1950\0\264\0\u198c"+
    "\0\264\0\u19c8\0\u1a04\0\264\0\u1a40\0\u1a7c\0\264\0\u1ab8"+
    "\0\u1af4\0\u1b30\0\u1b6c\0\u1ba8\0\264\0\u1be4\0\u1c20\0\264"+
    "\0\u1c5c\0\264\0\264\0\264\0\264\0\264\0\264\0\u1c98"+
    "\0\u1cd4\0\264\0\u1d10\0\264\0\264\0\264";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[182];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\3\4\1\5\1\6\1\4\1\7\1\10"+
    "\1\11\1\4\1\12\1\13\1\14\1\15\1\4\1\16"+
    "\1\17\1\20\1\4\1\21\1\22\2\4\1\23\1\4"+
    "\1\24\1\25\1\4\1\26\2\4\1\27\1\30\1\4"+
    "\1\31\2\2\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\75\0"+
    "\1\3\2\0\1\57\3\0\4\60\7\0\1\57\16\0"+
    "\1\3\4\0\1\61\25\0\4\4\1\0\6\4\2\0"+
    "\26\4\35\0\1\62\43\0\1\63\23\0\4\4\1\0"+
    "\2\4\1\64\3\4\2\0\2\4\1\65\23\4\31\0"+
    "\4\4\1\0\6\4\2\0\2\4\1\66\23\4\31\0"+
    "\4\4\1\0\6\4\2\0\26\4\1\67\30\0\4\4"+
    "\1\0\6\4\2\0\12\4\1\70\13\4\45\0\1\2"+
    "\57\0\4\4\1\0\4\4\1\71\1\4\2\0\26\4"+
    "\31\0\4\4\1\0\6\4\2\0\21\4\1\72\4\4"+
    "\31\0\4\4\1\0\6\4\2\0\4\4\1\73\21\4"+
    "\31\0\4\4\1\0\6\4\2\0\5\4\1\74\20\4"+
    "\31\0\4\4\1\0\2\4\1\75\3\4\2\0\12\4"+
    "\1\76\13\4\31\0\4\4\1\0\6\4\2\0\1\77"+
    "\1\4\1\100\6\4\1\101\14\4\31\0\4\4\1\0"+
    "\6\4\2\0\1\4\1\102\7\4\1\103\4\4\1\104"+
    "\1\4\1\105\5\4\31\0\4\4\1\0\6\4\2\0"+
    "\2\4\1\106\2\4\1\107\20\4\31\0\4\4\1\0"+
    "\6\4\2\0\2\4\1\110\23\4\31\0\4\4\1\0"+
    "\1\111\5\4\2\0\12\4\1\112\13\4\31\0\4\4"+
    "\1\0\6\4\2\0\11\4\1\113\14\4\31\0\4\4"+
    "\1\0\6\4\2\0\2\4\1\114\23\4\31\0\1\3"+
    "\2\0\1\57\3\0\4\60\7\0\1\57\16\0\1\3"+
    "\1\115\3\0\1\61\24\0\44\116\1\0\1\117\26\116"+
    "\1\0\1\61\40\0\1\61\4\0\1\120\24\0\46\121"+
    "\1\0\1\121\1\122\23\121\51\0\1\123\4\0\1\124"+
    "\67\0\1\125\3\0\1\126\70\0\1\127\74\0\1\130"+
    "\74\0\1\131\74\0\1\132\73\0\1\133\16\0\1\134"+
    "\3\0\1\135\34\0\1\134\10\0\1\135\30\0\4\60"+
    "\61\0\1\61\2\0\1\57\1\0\4\136\11\0\1\57"+
    "\16\0\1\61\32\0\4\4\1\0\6\4\2\0\2\4"+
    "\1\137\23\4\31\0\4\4\1\0\6\4\2\0\4\4"+
    "\1\140\21\4\31\0\4\4\1\0\6\4\2\0\12\4"+
    "\1\141\13\4\31\0\4\4\1\0\6\4\2\0\10\4"+
    "\1\142\5\4\1\143\7\4\31\0\4\4\1\0\6\4"+
    "\2\0\1\4\1\144\24\4\31\0\4\4\1\0\6\4"+
    "\2\0\22\4\1\145\3\4\31\0\4\4\1\0\6\4"+
    "\2\0\5\4\1\146\20\4\31\0\4\4\1\0\6\4"+
    "\2\0\1\4\1\147\13\4\1\150\10\4\31\0\4\4"+
    "\1\0\6\4\2\0\10\4\1\151\15\4\31\0\4\4"+
    "\1\0\4\4\1\152\1\4\2\0\26\4\31\0\4\4"+
    "\1\0\6\4\2\0\10\4\1\153\15\4\31\0\4\4"+
    "\1\0\6\4\2\0\12\4\1\154\13\4\31\0\4\4"+
    "\1\0\6\4\2\0\1\155\25\4\31\0\4\4\1\0"+
    "\6\4\2\0\1\156\3\4\1\157\21\4\31\0\4\4"+
    "\1\0\6\4\2\0\2\4\1\160\23\4\31\0\4\4"+
    "\1\0\6\4\2\0\15\4\1\161\1\4\1\162\6\4"+
    "\31\0\4\4\1\0\6\4\2\0\16\4\1\163\7\4"+
    "\31\0\4\4\1\0\4\4\1\164\1\4\2\0\26\4"+
    "\31\0\4\4\1\0\1\165\5\4\2\0\26\4\31\0"+
    "\4\4\1\0\6\4\2\0\1\4\1\166\24\4\31\0"+
    "\4\4\1\0\6\4\2\0\1\4\1\167\24\4\31\0"+
    "\4\4\1\0\6\4\2\0\16\4\1\170\7\4\31\0"+
    "\4\4\1\0\6\4\2\0\16\4\1\171\7\4\31\0"+
    "\1\172\1\0\2\172\1\0\2\172\6\0\1\172\2\0"+
    "\1\172\1\0\1\172\1\0\1\172\3\0\1\172\10\0"+
    "\1\172\31\0\44\116\1\136\1\117\74\116\1\0\25\116"+
    "\47\0\1\173\25\0\1\134\4\0\4\136\30\0\1\134"+
    "\32\0\1\134\40\0\1\134\32\0\4\4\1\0\6\4"+
    "\2\0\1\174\25\4\31\0\4\4\1\0\6\4\2\0"+
    "\15\4\1\175\10\4\31\0\4\4\1\0\6\4\2\0"+
    "\16\4\1\176\7\4\31\0\4\4\1\0\6\4\2\0"+
    "\2\4\1\177\23\4\31\0\4\4\1\0\6\4\2\0"+
    "\2\4\1\200\23\4\31\0\4\4\1\0\6\4\2\0"+
    "\5\4\1\201\20\4\31\0\4\4\1\0\6\4\2\0"+
    "\1\202\25\4\31\0\4\4\1\0\4\4\1\203\1\4"+
    "\2\0\26\4\31\0\4\4\1\0\6\4\2\0\16\4"+
    "\1\204\7\4\31\0\4\4\1\0\6\4\2\0\5\4"+
    "\1\205\20\4\31\0\4\4\1\0\6\4\2\0\14\4"+
    "\1\206\11\4\31\0\4\4\1\0\6\4\2\0\5\4"+
    "\1\207\20\4\31\0\4\4\1\0\6\4\2\0\10\4"+
    "\1\210\15\4\31\0\4\4\1\0\6\4\2\0\4\4"+
    "\1\211\21\4\31\0\4\4\1\0\6\4\2\0\1\4"+
    "\1\212\24\4\31\0\4\4\1\0\4\4\1\213\1\4"+
    "\2\0\26\4\31\0\4\4\1\0\6\4\2\0\4\4"+
    "\1\214\21\4\31\0\4\4\1\0\6\4\2\0\12\4"+
    "\1\215\13\4\31\0\4\4\1\0\6\4\2\0\5\4"+
    "\1\216\20\4\31\0\4\4\1\0\6\4\2\0\1\4"+
    "\1\217\24\4\31\0\4\4\1\0\6\4\2\0\3\4"+
    "\1\220\22\4\31\0\4\4\1\0\6\4\2\0\1\221"+
    "\25\4\31\0\4\4\1\0\6\4\2\0\2\4\1\222"+
    "\23\4\31\0\4\4\1\0\2\4\1\223\3\4\2\0"+
    "\26\4\31\0\4\4\1\0\6\4\2\0\13\4\1\224"+
    "\12\4\31\0\1\172\1\0\2\172\1\0\2\172\4\60"+
    "\2\0\1\172\2\0\1\172\1\0\1\172\1\0\1\172"+
    "\3\0\1\172\10\0\1\172\32\0\4\4\1\0\6\4"+
    "\2\0\1\4\1\225\24\4\31\0\4\4\1\0\6\4"+
    "\2\0\15\4\1\226\10\4\31\0\4\4\1\0\6\4"+
    "\2\0\12\4\1\227\13\4\31\0\4\4\1\0\6\4"+
    "\2\0\13\4\1\230\12\4\31\0\4\4\1\0\6\4"+
    "\2\0\6\4\1\231\17\4\31\0\4\4\1\0\6\4"+
    "\2\0\4\4\1\232\21\4\31\0\4\4\1\0\6\4"+
    "\2\0\10\4\1\233\15\4\31\0\4\4\1\0\6\4"+
    "\2\0\1\4\1\234\24\4\31\0\4\4\1\0\6\4"+
    "\2\0\16\4\1\235\7\4\31\0\4\4\1\0\6\4"+
    "\2\0\7\4\1\236\16\4\31\0\4\4\1\0\6\4"+
    "\2\0\1\4\1\237\24\4\31\0\4\4\1\0\6\4"+
    "\2\0\5\4\1\240\20\4\31\0\4\4\1\0\6\4"+
    "\2\0\2\4\1\241\23\4\31\0\4\4\1\0\6\4"+
    "\2\0\7\4\1\242\16\4\31\0\4\4\1\0\2\4"+
    "\1\243\3\4\2\0\26\4\31\0\4\4\1\0\4\4"+
    "\1\244\1\4\2\0\26\4\31\0\4\4\1\0\6\4"+
    "\2\0\5\4\1\245\20\4\31\0\4\4\1\0\6\4"+
    "\2\0\12\4\1\246\13\4\31\0\4\4\1\0\6\4"+
    "\2\0\5\4\1\247\20\4\31\0\4\4\1\0\6\4"+
    "\2\0\12\4\1\250\13\4\31\0\4\4\1\0\6\4"+
    "\2\0\1\4\1\251\24\4\31\0\4\4\1\0\6\4"+
    "\2\0\7\4\1\252\16\4\31\0\4\4\1\0\6\4"+
    "\2\0\1\4\1\253\24\4\31\0\4\4\1\0\6\4"+
    "\2\0\13\4\1\254\12\4\31\0\4\4\1\0\1\255"+
    "\5\4\2\0\26\4\31\0\4\4\1\0\6\4\2\0"+
    "\11\4\1\256\14\4\31\0\4\4\1\0\6\4\2\0"+
    "\5\4\1\257\20\4\31\0\4\4\1\0\2\4\1\260"+
    "\3\4\2\0\26\4\31\0\4\4\1\0\6\4\2\0"+
    "\5\4\1\261\20\4\31\0\4\4\1\0\1\262\5\4"+
    "\2\0\26\4\31\0\4\4\1\0\6\4\2\0\5\4"+
    "\1\263\20\4\31\0\4\4\1\0\6\4\2\0\1\4"+
    "\1\264\24\4\31\0\4\4\1\0\6\4\2\0\13\4"+
    "\1\265\12\4\31\0\4\4\1\0\6\4\2\0\4\4"+
    "\1\266\21\4\30\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7500];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\27\1\14\11\1\0\2\1"+
    "\2\11\3\1\1\0\25\1\5\0\1\1\11\11\1\1"+
    "\1\0\1\11\34\1\1\11\73\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[182];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 152) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 29: 
          { return Parser.DO;
          }
        case 69: break;
        case 52: 
          { return Parser.FLOAT;
          }
        case 70: break;
        case 16: 
          { return Parser.BRACELEFT;
          }
        case 71: break;
        case 57: 
          { return Parser.WHILE;
          }
        case 72: break;
        case 4: 
          { return Parser.MINUS;
          }
        case 73: break;
        case 10: 
          { return Parser.PLUS;
          }
        case 74: break;
        case 58: 
          { return Parser.RETURN;
          }
        case 75: break;
        case 26: 
          { return Parser.QUESTION;
          }
        case 76: break;
        case 53: 
          { return Parser.UNION;
          }
        case 77: break;
        case 42: 
          { return Parser.INT;
          }
        case 78: break;
        case 2: 
          { if(yyparser!=null) yyparser.yylval = new ParserVal(yytext()); return Parser.CONSTANT;
          }
        case 79: break;
        case 67: 
          { return Parser.UNSIGNED;
          }
        case 80: break;
        case 44: 
          { return Parser.LONG;
          }
        case 81: break;
        case 60: 
          { return Parser.STRUCT;
          }
        case 82: break;
        case 54: 
          { return Parser.BREAK;
          }
        case 83: break;
        case 55: 
          { return Parser.CONST;
          }
        case 84: break;
        case 36: 
          { return Parser.INC_OP;
          }
        case 85: break;
        case 6: 
          { return Parser.STAR;
          }
        case 86: break;
        case 50: 
          { return Parser.GOTO;
          }
        case 87: break;
        case 28: 
          { return Parser.PTR_OP;
          }
        case 88: break;
        case 22: 
          { return Parser.BRACKETLEFT;
          }
        case 89: break;
        case 13: 
          { return Parser.EQUAL;
          }
        case 90: break;
        case 11: 
          { return Parser.AMP;
          }
        case 91: break;
        case 59: 
          { return Parser.STATIC;
          }
        case 92: break;
        case 34: 
          { return Parser.LEFT_OP;
          }
        case 93: break;
        case 25: 
          { return Parser.CARET;
          }
        case 94: break;
        case 32: 
          { return Parser.RIGHT_OP;
          }
        case 95: break;
        case 45: 
          { return Parser.AUTO;
          }
        case 96: break;
        case 38: 
          { return Parser.OR_OP;
          }
        case 97: break;
        case 35: 
          { return Parser.LE_OP;
          }
        case 98: break;
        case 40: 
          { return Parser.NE_OP;
          }
        case 99: break;
        case 43: 
          { return Parser.ELLIPSIS;
          }
        case 100: break;
        case 14: 
          { return Parser.EXCL;
          }
        case 101: break;
        case 30: 
          { return Parser.IF;
          }
        case 102: break;
        case 12: 
          { return Parser.BAR;
          }
        case 103: break;
        case 39: 
          { return Parser.EQ_OP;
          }
        case 104: break;
        case 41: 
          { return Parser.FOR;
          }
        case 105: break;
        case 3: 
          { if(yyparser!=null) yyparser.yylval = new ParserVal(yytext()); return Parser.IDENTIFIER;
          }
        case 106: break;
        case 27: 
          { return Parser.DEC_OP;
          }
        case 107: break;
        case 9: 
          { return Parser.LESS;
          }
        case 108: break;
        case 65: 
          { return Parser.TYPEDEF;
          }
        case 109: break;
        case 31: 
          { return Parser.STRING_LITERAL;
          }
        case 110: break;
        case 8: 
          { return Parser.GREATER;
          }
        case 111: break;
        case 24: 
          { return Parser.PERCENT;
          }
        case 112: break;
        case 21: 
          { return Parser.RBRIGHT;
          }
        case 113: break;
        case 20: 
          { return Parser.RBLEFT;
          }
        case 114: break;
        case 61: 
          { return Parser.SIGNED;
          }
        case 115: break;
        case 49: 
          { return Parser.CHAR;
          }
        case 116: break;
        case 18: 
          { return Parser.COMMA;
          }
        case 117: break;
        case 63: 
          { return Parser.SWITCH;
          }
        case 118: break;
        case 68: 
          { return Parser.REGISTER;
          }
        case 119: break;
        case 33: 
          { return Parser.GE_OP;
          }
        case 120: break;
        case 17: 
          { return Parser.BRACERIGHT;
          }
        case 121: break;
        case 19: 
          { return Parser.COLON;
          }
        case 122: break;
        case 66: 
          { return Parser.DEFAULT;
          }
        case 123: break;
        case 64: 
          { return Parser.DOUBLE;
          }
        case 124: break;
        case 5: 
          { return Parser.SLASH;
          }
        case 125: break;
        case 23: 
          { return Parser.BRACKETRIGHT;
          }
        case 126: break;
        case 47: 
          { return Parser.ENUM;
          }
        case 127: break;
        case 37: 
          { return Parser.AND_OP;
          }
        case 128: break;
        case 56: 
          { return Parser.SHORT;
          }
        case 129: break;
        case 46: 
          { return Parser.ELSE;
          }
        case 130: break;
        case 62: 
          { return Parser.SIZEOF;
          }
        case 131: break;
        case 48: 
          { return Parser.CASE;
          }
        case 132: break;
        case 15: 
          { return Parser.SEMICOLON;
          }
        case 133: break;
        case 51: 
          { return Parser.VOID;
          }
        case 134: break;
        case 7: 
          { return Parser.DOT;
          }
        case 135: break;
        case 1: 
          { 
          }
        case 136: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
