/* The following code was generated by JFlex 1.4.3 on 10/24/15 3:57 PM */

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright (C) 2000 Gerwin Klein <lsf@jflex.de>                          *
 * All rights reserved.                                                    *
 *                                                                         *
 * Thanks to Larry Bell and Bob Jamison for suggestions and comments.      *
 *                                                                         *
 * License: BSD                                                            *
 *                                                                         *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
package edu.eltech.moevm.autogen;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/24/15 3:57 PM from the specification file
 * <tt>grammar.flex</tt>
 */
class Yylex {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\46\1\0\1\0\23\0\1\0\1\61\1\50\2\0"+
    "\1\55\1\56\1\44\1\67\1\70\1\14\1\54\1\65\1\4\1\47"+
    "\1\13\1\42\11\1\1\66\1\62\1\53\1\52\1\51\1\74\1\0"+
    "\4\2\1\3\1\6\5\0\1\10\10\0\1\12\2\0\1\43\2\0"+
    "\1\71\1\45\1\72\1\57\1\0\1\0\1\15\1\20\1\24\1\31"+
    "\1\22\1\5\1\34\1\26\1\30\1\0\1\23\1\7\1\32\1\27"+
    "\1\17\1\40\1\0\1\21\1\25\1\16\1\11\1\41\1\36\1\33"+
    "\1\37\1\35\1\63\1\60\1\64\1\73\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\4\1\1\4\1\5\14\1"+
    "\1\2\1\1\1\6\1\1\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\0\2\2\1\33\1\34\1\35\5\0\1\36\1\37"+
    "\16\0\1\40\1\0\1\41\11\0\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\2\1\0\1\2\1\0"+
    "\1\61\24\0\1\62\6\0\1\2\1\63\1\64\1\65"+
    "\1\0\1\66\2\0\1\67\4\0\1\70\1\71\1\0"+
    "\1\72\2\0\1\73\10\0\1\74\2\0\1\75\1\76"+
    "\1\0\1\77\1\0\1\100\4\0\1\101\2\0\1\102"+
    "\5\0\1\103\3\0\1\104\1\0\1\105\1\0\1\106"+
    "\1\107\1\110\1\111\1\112\1\113\3\0\1\114\2\0"+
    "\1\115\1\0\1\116\1\117\1\120\1\121";

  private static int [] zzUnpackAction() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\75\0\172\0\267\0\364\0\u0131\0\u016e\0\u01ab"+
    "\0\u01e8\0\u0225\0\u0262\0\u029f\0\u02dc\0\u0319\0\u0356\0\u0393"+
    "\0\u03d0\0\u040d\0\u044a\0\u0487\0\u04c4\0\u0501\0\u053e\0\u057b"+
    "\0\u05b8\0\u05f5\0\u0632\0\u066f\0\u06ac\0\u06e9\0\u0726\0\u0763"+
    "\0\u07a0\0\u07dd\0\u081a\0\75\0\75\0\75\0\75\0\75"+
    "\0\75\0\75\0\75\0\75\0\75\0\75\0\u0857\0\u0894"+
    "\0\u08d1\0\75\0\75\0\75\0\u090e\0\u094b\0\u0988\0\u057b"+
    "\0\u09c5\0\75\0\75\0\u0a02\0\u0a3f\0\u0a7c\0\u0ab9\0\u0af6"+
    "\0\u0b33\0\u0b70\0\u0bad\0\u0bea\0\u0c27\0\u0c64\0\u0ca1\0\u0cde"+
    "\0\u0d1b\0\75\0\u0d58\0\u0d95\0\u0dd2\0\u0e0f\0\u0e4c\0\u0e89"+
    "\0\u0ec6\0\u0f03\0\u0f40\0\u0f7d\0\u05f5\0\u05f5\0\u0fba\0\75"+
    "\0\75\0\75\0\u0ff7\0\75\0\75\0\75\0\75\0\75"+
    "\0\75\0\75\0\75\0\75\0\u1034\0\u1071\0\75\0\u10ae"+
    "\0\75\0\u10eb\0\u1128\0\u1165\0\u11a2\0\u11df\0\u121c\0\u1259"+
    "\0\u1296\0\u12d3\0\u1310\0\u134d\0\u138a\0\u13c7\0\u1404\0\u1441"+
    "\0\u147e\0\u14bb\0\u14f8\0\u1535\0\u1572\0\75\0\u15af\0\u15ec"+
    "\0\u1629\0\u1666\0\u16a3\0\u16e0\0\u171d\0\75\0\75\0\75"+
    "\0\u175a\0\75\0\u1797\0\u17d4\0\75\0\u1811\0\u184e\0\u188b"+
    "\0\u18c8\0\75\0\75\0\u1905\0\75\0\u1942\0\u197f\0\75"+
    "\0\u19bc\0\u19f9\0\u1a36\0\u1a73\0\u1ab0\0\u1aed\0\u1b2a\0\u1b67"+
    "\0\75\0\u1ba4\0\u1be1\0\75\0\75\0\u1c1e\0\75\0\u1c5b"+
    "\0\75\0\u1c98\0\u1cd5\0\u1d12\0\u1d4f\0\75\0\u1d8c\0\u1dc9"+
    "\0\75\0\u1e06\0\u1e43\0\u1e80\0\u1ebd\0\u1efa\0\75\0\u1f37"+
    "\0\u1f74\0\u1fb1\0\75\0\u1fee\0\75\0\u202b\0\75\0\75"+
    "\0\75\0\75\0\75\0\75\0\u2068\0\u20a5\0\u20e2\0\75"+
    "\0\u211f\0\u215c\0\75\0\u2199\0\75\0\75\0\75\0\75";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\2\1\4\1\5\1\2\1\6\1\7"+
    "\1\10\1\2\1\11\1\12\1\13\1\14\1\2\1\15"+
    "\1\16\1\17\1\2\1\20\1\21\2\2\1\22\1\23"+
    "\2\2\1\24\1\2\1\25\2\2\1\26\1\27\1\2"+
    "\1\30\2\2\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\76\0\1\3\1\0\1\57\3\0\4\60\7\0\1\57"+
    "\17\0\1\3\4\0\1\61\31\0\1\62\44\0\1\63"+
    "\1\64\31\0\1\65\7\0\1\66\74\0\1\67\121\0"+
    "\1\70\57\0\1\71\61\0\1\2\35\0\1\72\74\0"+
    "\1\73\33\0\1\74\122\0\1\75\56\0\1\76\75\0"+
    "\1\77\61\0\1\100\17\0\1\101\3\0\1\102\56\0"+
    "\1\103\1\0\1\104\6\0\1\105\64\0\1\106\7\0"+
    "\1\107\1\0\1\110\5\0\1\111\43\0\1\112\21\0"+
    "\1\113\64\0\1\114\2\0\1\115\71\0\1\116\103\0"+
    "\1\117\65\0\1\120\56\0\1\3\1\0\1\57\3\0"+
    "\4\60\7\0\1\57\10\0\1\121\6\0\1\3\1\121"+
    "\3\0\1\61\25\0\44\122\1\0\1\123\27\122\1\0"+
    "\1\61\40\0\1\61\4\0\1\124\25\0\46\125\1\0"+
    "\1\125\1\126\24\125\51\0\1\127\1\130\74\0\1\131"+
    "\74\0\1\132\1\133\73\0\1\134\1\0\1\135\72\0"+
    "\1\136\74\0\1\137\3\0\1\140\70\0\1\141\74\0"+
    "\1\142\5\0\1\143\66\0\1\144\23\0\1\145\2\0"+
    "\1\146\35\0\1\145\11\0\1\146\27\0\4\60\63\0"+
    "\1\61\1\0\1\57\1\0\4\147\11\0\1\57\17\0"+
    "\1\61\51\0\1\150\76\0\1\151\102\0\1\152\72\0"+
    "\1\153\2\0\1\154\62\0\1\155\116\0\1\156\56\0"+
    "\1\157\70\0\1\160\15\0\1\161\65\0\1\162\60\0"+
    "\1\163\101\0\1\164\103\0\1\165\76\0\1\166\62\0"+
    "\1\167\74\0\1\170\3\0\1\171\72\0\1\172\111\0"+
    "\1\173\1\174\67\0\1\175\62\0\1\176\67\0\1\177"+
    "\70\0\1\200\105\0\1\201\106\0\1\202\53\0\1\203"+
    "\20\0\1\204\45\0\3\205\1\0\2\205\6\0\1\205"+
    "\2\0\1\205\1\0\1\205\1\0\1\205\4\0\1\205"+
    "\10\0\1\205\32\0\44\122\1\147\1\123\75\122\1\0"+
    "\26\122\47\0\1\206\77\0\1\207\74\0\1\210\23\0"+
    "\1\145\3\0\4\147\31\0\1\145\33\0\1\145\40\0"+
    "\1\145\47\0\1\211\113\0\1\212\70\0\1\213\63\0"+
    "\1\214\74\0\1\215\77\0\1\216\67\0\1\217\70\0"+
    "\1\220\113\0\1\221\66\0\1\222\104\0\1\223\64\0"+
    "\1\224\74\0\1\225\70\0\1\226\6\0\1\227\70\0"+
    "\1\230\71\0\1\231\67\0\1\232\104\0\1\233\102\0"+
    "\1\234\67\0\1\235\70\0\1\236\76\0\1\237\71\0"+
    "\1\240\76\0\1\241\64\0\1\242\102\0\1\243\110\0"+
    "\1\244\44\0\3\205\1\0\2\205\4\60\2\0\1\205"+
    "\2\0\1\205\1\0\1\205\1\0\1\205\4\0\1\205"+
    "\10\0\1\205\50\0\1\245\112\0\1\246\67\0\1\247"+
    "\76\0\1\250\66\0\1\251\72\0\1\252\100\0\1\253"+
    "\70\0\1\254\103\0\1\255\62\0\1\256\106\0\1\257"+
    "\70\0\1\260\66\0\1\261\100\0\1\262\71\0\1\263"+
    "\101\0\1\264\57\0\1\265\76\0\1\266\105\0\1\267"+
    "\70\0\1\270\105\0\1\271\67\0\1\272\101\0\1\273"+
    "\63\0\1\274\105\0\1\275\74\0\1\276\71\0\1\277"+
    "\66\0\1\300\107\0\1\301\50\0\1\302\115\0\1\303"+
    "\70\0\1\304\61\0\1\305\115\0\1\306\66\0\1\307"+
    "\57\0\1\310\111\0\1\311\63\0\1\312\101\0\1\313"+
    "\65\0\1\314\116\0\1\315\64\0\1\316\75\0\1\317"+
    "\74\0\1\320\52\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8662];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\41\1\13\11\1\0\2\1\3\11\5\0"+
    "\2\11\16\0\1\11\1\0\1\1\11\0\2\1\3\11"+
    "\1\1\11\11\1\1\1\0\1\11\1\0\1\11\24\0"+
    "\1\11\6\0\1\1\3\11\1\0\1\11\2\0\1\11"+
    "\4\0\2\11\1\0\1\11\2\0\1\11\10\0\1\11"+
    "\2\0\2\11\1\0\1\11\1\0\1\11\4\0\1\11"+
    "\2\0\1\11\5\0\1\11\3\0\1\11\1\0\1\11"+
    "\1\0\6\11\3\0\1\11\2\0\1\11\1\0\4\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private Parser yyparser;

  public Yylex(java.io.Reader r, Parser yyparser) {
    this(r);
    this.yyparser = yyparser;
  }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 154) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 25: 
          { return Parser.TILDE;
          }
        case 82: break;
        case 17: 
          { return Parser.BRACELEFT;
          }
        case 83: break;
        case 4: 
          { return Parser.SLASH;
          }
        case 84: break;
        case 30: 
          { return Parser.DIV_ASSIGN;
          }
        case 85: break;
        case 2: 
          { return Parser.CONSTANT;
          }
        case 86: break;
        case 36: 
          { return Parser.GE_OP;
          }
        case 87: break;
        case 43: 
          { return Parser.AND_ASSIGN;
          }
        case 88: break;
        case 9: 
          { return Parser.LESS;
          }
        case 89: break;
        case 46: 
          { return Parser.OR_ASSIGN;
          }
        case 90: break;
        case 12: 
          { return Parser.AMP;
          }
        case 91: break;
        case 44: 
          { return Parser.AND_OP;
          }
        case 92: break;
        case 26: 
          { return Parser.QUESTION;
          }
        case 93: break;
        case 3: 
          { return Parser.MINUS;
          }
        case 94: break;
        case 24: 
          { return Parser.BRACKETRIGHT;
          }
        case 95: break;
        case 14: 
          { return Parser.BAR;
          }
        case 96: break;
        case 48: 
          { return Parser.NE_OP;
          }
        case 97: break;
        case 35: 
          { return Parser.RIGHT_OP;
          }
        case 98: break;
        case 55: 
          { return Parser.AUTO;
          }
        case 99: break;
        case 61: 
          { return Parser.VOID;
          }
        case 100: break;
        case 31: 
          { return Parser.MUL_ASSIGN;
          }
        case 101: break;
        case 81: 
          { return Parser.VOLATILE;
          }
        case 102: break;
        case 66: 
          { return Parser.SHORT;
          }
        case 103: break;
        case 45: 
          { return Parser.XOR_ASSIGN;
          }
        case 104: break;
        case 7: 
          { return Parser.GREATER;
          }
        case 105: break;
        case 78: 
          { return Parser.UNSIGNED;
          }
        case 106: break;
        case 72: 
          { return Parser.SIGNED;
          }
        case 107: break;
        case 11: 
          { return Parser.PERCENT;
          }
        case 108: break;
        case 8: 
          { return Parser.EQUAL;
          }
        case 109: break;
        case 63: 
          { return Parser.UNION;
          }
        case 110: break;
        case 67: 
          { return Parser.WHILE;
          }
        case 111: break;
        case 42: 
          { return Parser.MOD_ASSIGN;
          }
        case 112: break;
        case 65: 
          { return Parser.CONST;
          }
        case 113: break;
        case 70: 
          { return Parser.STATIC;
          }
        case 114: break;
        case 27: 
          { return Parser.DEC_OP;
          }
        case 115: break;
        case 16: 
          { return Parser.SEMICOLON;
          }
        case 116: break;
        case 20: 
          { return Parser.COLON;
          }
        case 117: break;
        case 64: 
          { return Parser.BREAK;
          }
        case 118: break;
        case 23: 
          { return Parser.BRACKETLEFT;
          }
        case 119: break;
        case 79: 
          { return Parser.REGISTER;
          }
        case 120: break;
        case 54: 
          { return Parser.LONG;
          }
        case 121: break;
        case 10: 
          { return Parser.PLUS;
          }
        case 122: break;
        case 6: 
          { return Parser.DOT;
          }
        case 123: break;
        case 69: 
          { return Parser.EXTERN;
          }
        case 124: break;
        case 76: 
          { return Parser.TYPEDEF;
          }
        case 125: break;
        case 37: 
          { return Parser.EQ_OP;
          }
        case 126: break;
        case 13: 
          { return Parser.CARET;
          }
        case 127: break;
        case 15: 
          { return Parser.EXCL;
          }
        case 128: break;
        case 57: 
          { return Parser.ENUM;
          }
        case 129: break;
        case 75: 
          { return Parser.DOUBLE;
          }
        case 130: break;
        case 59: 
          { return Parser.CHAR;
          }
        case 131: break;
        case 19: 
          { return Parser.COMMA;
          }
        case 132: break;
        case 71: 
          { return Parser.STRUCT;
          }
        case 133: break;
        case 68: 
          { return Parser.RETURN;
          }
        case 134: break;
        case 50: 
          { return Parser.INT;
          }
        case 135: break;
        case 21: 
          { return Parser.RBLEFT;
          }
        case 136: break;
        case 28: 
          { return Parser.PTR_OP;
          }
        case 137: break;
        case 33: 
          { return Parser.DO;
          }
        case 138: break;
        case 52: 
          { return Parser.RIGHT_ASSIGN;
          }
        case 139: break;
        case 74: 
          { return Parser.SWITCH;
          }
        case 140: break;
        case 34: 
          { return Parser.STRING_LITERAL;
          }
        case 141: break;
        case 77: 
          { return Parser.DEFAULT;
          }
        case 142: break;
        case 39: 
          { return Parser.LEFT_OP;
          }
        case 143: break;
        case 40: 
          { return Parser.ADD_ASSIGN;
          }
        case 144: break;
        case 41: 
          { return Parser.INC_OP;
          }
        case 145: break;
        case 49: 
          { return Parser.FOR;
          }
        case 146: break;
        case 73: 
          { return Parser.SIZEOF;
          }
        case 147: break;
        case 80: 
          { return Parser.CONTINUE;
          }
        case 148: break;
        case 56: 
          { return Parser.ELSE;
          }
        case 149: break;
        case 38: 
          { return Parser.LE_OP;
          }
        case 150: break;
        case 47: 
          { return Parser.OR_OP;
          }
        case 151: break;
        case 5: 
          { return Parser.STAR;
          }
        case 152: break;
        case 60: 
          { return Parser.GOTO;
          }
        case 153: break;
        case 22: 
          { return Parser.RBRIGHT;
          }
        case 154: break;
        case 58: 
          { return Parser.CASE;
          }
        case 155: break;
        case 51: 
          { return Parser.ELLIPSIS;
          }
        case 156: break;
        case 29: 
          { return Parser.SUB_ASSIGN;
          }
        case 157: break;
        case 32: 
          { return Parser.IF;
          }
        case 158: break;
        case 53: 
          { return Parser.LEFT_ASSIGN;
          }
        case 159: break;
        case 62: 
          { return Parser.FLOAT;
          }
        case 160: break;
        case 18: 
          { return Parser.BRACERIGHT;
          }
        case 161: break;
        case 1: 
          { 
          }
        case 162: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return 0; }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
